version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo "Using Java 17"

  build:
    commands:
      - chmod +x ./gradlew
      - ./gradlew clean build -x test

artifacts:
  files:
    - appspec.yml
    - deploy-scripts/**/*
    - build/libs/*.jar