version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo "Using Java 17"
  build:
    commands:
      - echo "Building Spring Boot application"
      - chmod +x ./gradlew
      - ./gradlew build -x test
artifacts:
  files:
    - build/libs/*.jar
